#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Analyze shortest-path length distribution from an HTSIM topology file
generated by expander_eps.py, and plot how many src-dst pairs fall into
each shortest-path length.

Default behavior:
- Treat the last H nodes as Agg endpoints (because the file header stores H,
  and the generator writes nodes in the order ToR, EPS, Agg).
- Count Agg-to-Agg pairs, which matches the routing semantics of the generator.

Input topology format (wr0 / topology-only):
- line 1: H dl ul ntor N
- next N lines: NxN adjacency matrix

Outputs:
- <prefix>_distance_hist.png
- <prefix>_distance_stats.csv
"""

import argparse
import csv
from collections import Counter
from pathlib import Path

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np


def read_topology(topofile: str):
    path = Path(topofile)
    if not path.exists():
        raise FileNotFoundError(f"Topology file not found: {path}")

    with path.open("r", encoding="utf-8") as f:
        header = f.readline().strip().split()
        if len(header) < 5:
            raise ValueError(
                "Header must contain at least 5 integers: H dl ul ntor N"
            )

        H, dl, ul, ntor, N = map(int, header[:5])

        rows = []
        for i in range(N):
            line = f.readline()
            if not line:
                raise ValueError(
                    f"Unexpected EOF while reading adjacency matrix, expected {N} rows"
                )
            row = [int(x) for x in line.strip().split()]
            if len(row) != N:
                raise ValueError(
                    f"Adjacency row {i} has {len(row)} entries, expected {N}"
                )
            rows.append(row)

    A = np.array(rows, dtype=int)
    if not np.array_equal(A, A.T):
        raise ValueError("Adjacency matrix is not symmetric")
    if np.any(np.diag(A) != 0):
        raise ValueError("Adjacency matrix diagonal must be all zeros")

    G = nx.from_numpy_array(A)
    return G, H, dl, ul, ntor, N


def count_pair_distances(G: nx.Graph, endpoint_nodes, directed: bool = True):
    endpoint_set = set(endpoint_nodes)
    counter = Counter()
    total_distance = 0
    total_pairs = 0
    max_distance = 0

    for src in endpoint_nodes:
        lengths = nx.single_source_shortest_path_length(G, src)
        for dst in endpoint_nodes:
            if src == dst:
                continue
            if dst not in lengths:
                raise ValueError(f"No path between endpoint {src} and {dst}")
            if not directed and src > dst:
                continue

            d = lengths[dst]
            counter[d] += 1
            total_distance += d
            total_pairs += 1
            if d > max_distance:
                max_distance = d

    mean_distance = total_distance / total_pairs if total_pairs else 0.0
    return counter, total_pairs, mean_distance, max_distance


def write_csv(counter: Counter, total_pairs: int, out_csv: Path):
    with out_csv.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["distance", "pair_count", "percentage"])
        for d in sorted(counter):
            c = counter[d]
            pct = 100.0 * c / total_pairs if total_pairs else 0.0
            writer.writerow([d, c, f"{pct:.6f}"])


def plot_distribution(counter: Counter, total_pairs: int, out_png: Path, title: str):
    distances = sorted(counter)
    counts = np.array([counter[d] for d in distances], dtype=np.int64)
    percentages = counts / total_pairs * 100.0 if total_pairs else np.zeros_like(counts, dtype=float)

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.6), constrained_layout=True)

    axes[0].bar(distances, counts)
    axes[0].set_xlabel("Shortest-path length (hops)")
    axes[0].set_ylabel("Number of src-dst pairs")
    axes[0].set_title("Pair count by shortest-path length")
    axes[0].set_xticks(distances)

    axes[1].bar(distances, percentages)
    axes[1].set_xlabel("Shortest-path length (hops)")
    axes[1].set_ylabel("Percentage of src-dst pairs (%)")
    axes[1].set_title("Pair percentage by shortest-path length")
    axes[1].set_xticks(distances)

    fig.suptitle(title, fontsize=12)
    fig.savefig(out_png, dpi=300)
    plt.close(fig)


def main():
    parser = argparse.ArgumentParser(
        description="Analyze shortest-path length distribution from an HTSIM topology file."
    )
    parser.add_argument(
        "topology_file",
        type=str,
        help="Path to the topology txt file generated by expander_eps.py",
    )
    parser.add_argument(
        "--pair-scope",
        choices=["agg", "all"],
        default="agg",
        help="Count distances among Agg endpoints only (default) or among all graph nodes.",
    )
    parser.add_argument(
        "--undirected",
        action="store_true",
        help="Count unordered pairs instead of ordered src-dst pairs.",
    )
    parser.add_argument(
        "--output_prefix",
        type=str,
        default=None,
        help="Output prefix. Default: derived from topology filename.",
    )
    args = parser.parse_args()

    G, H, dl, ul, ntor, N = read_topology(args.topology_file)

    if args.pair_scope == "agg":
        # Generator writes nodes in the order: ToR, EPS, Agg.
        # Therefore the last H nodes are Agg nodes.
        endpoint_nodes = list(range(N - H, N))
        scope_desc = "Agg-to-Agg"
    else:
        endpoint_nodes = list(range(N))
        scope_desc = "All-node"

    counter, total_pairs, mean_distance, diameter = count_pair_distances(
        G,
        endpoint_nodes,
        directed=not args.undirected,
    )

    out_prefix = args.output_prefix
    if out_prefix is None:
        out_prefix = str(Path(args.topology_file).with_suffix(""))

    out_png = Path(out_prefix + "_distance_hist.png")
    out_csv = Path(out_prefix + "_distance_stats.csv")

    write_csv(counter, total_pairs, out_csv)
    plot_distribution(
        counter,
        total_pairs,
        out_png,
        title=f"{scope_desc} shortest-path distribution\n"
              f"pairs={total_pairs}, mean={mean_distance:.4f}, diameter={diameter}",
    )

    print("=== Topology Summary ===")
    print(f"File                : {args.topology_file}")
    print(f"N (graph nodes)     : {N}")
    print(f"H (Agg endpoints)   : {H}")
    print(f"dl / ul / ntor      : {dl} / {ul} / {ntor}")
    print(f"Pair scope          : {scope_desc}")
    print(f"Pair counting       : {'unordered' if args.undirected else 'ordered'}")
    print(f"Total pairs         : {total_pairs}")
    print(f"Mean distance       : {mean_distance:.6f}")
    print(f"Diameter            : {diameter}")
    print("Distance histogram:")
    for d in sorted(counter):
        c = counter[d]
        pct = 100.0 * c / total_pairs if total_pairs else 0.0
        print(f"  hops={d:<2d} count={c:<10d} pct={pct:8.4f}%")

    print(f"\nSaved figure to: {out_png}")
    print(f"Saved CSV to   : {out_csv}")


if __name__ == "__main__":
    main()
